/**
 * Prometheus metrics server for the simulation.
 * Exposes /metrics on port 9099.
 * Run alongside the orchestrator if you want scrape-based metrics.
 */

import * as http from 'http';
import * as client from 'prom-client';

const registry = new client.Registry();
registry.setDefaultLabels({ service: 'simulation' });

// ── Metrics ──────────────────────────────────────────────────────────────────

export const simWorkflowTotal = new client.Counter({
  name: 'sim_workflow_total',
  help: 'Total number of simulation workflow executions',
  labelNames: ['workflow', 'persona', 'status'],
  registers: [registry],
});

export const simWorkflowDuration = new client.Histogram({
  name: 'sim_workflow_duration_seconds',
  help: 'Simulation workflow execution duration in seconds',
  labelNames: ['workflow', 'persona'],
  buckets: [0.1, 0.5, 1, 2, 5, 10],
  registers: [registry],
});

export const simActivePersonas = new client.Gauge({
  name: 'sim_active_personas',
  help: 'Number of currently active persona sessions',
  registers: [registry],
});

export const simUsersTotal = new client.Gauge({
  name: 'sim_users_total',
  help: 'Total number of simulation users by type',
  labelNames: ['type'],
  registers: [registry],
});

export const simInvitesSent = new client.Counter({
  name: 'sim_invites_sent_total',
  help: 'Total invite codes generated by persona',
  labelNames: ['persona'],
  registers: [registry],
});

export const simGeographicSpread = new client.Gauge({
  name: 'sim_geographic_spread',
  help: 'Number of simulation users per Bay Area region',
  labelNames: ['region'],
  registers: [registry],
});

export const simNetworkDepth = new client.Gauge({
  name: 'sim_network_depth',
  help: 'Maximum invite chain depth (0 = founders only)',
  registers: [registry],
});

// ── HTTP server ───────────────────────────────────────────────────────────────

const METRICS_PORT = 9099;

export function startMetricsServer() {
  const server = http.createServer(async (req, res) => {
    if (req.url === '/metrics' && req.method === 'GET') {
      res.setHeader('Content-Type', registry.contentType);
      res.end(await registry.metrics());
    } else if (req.url === '/health') {
      res.writeHead(200);
      res.end('ok');
    } else {
      res.writeHead(404);
      res.end();
    }
  });

  server.listen(METRICS_PORT, () => {
    console.log(`  📊 Metrics server: http://localhost:${METRICS_PORT}/metrics`);
  });

  return server;
}
