import { UISchema } from './types';

export const eventUISchema: UISchema = {
  type: 'event',
  version: 1,
  label: 'Event Help',
  icon: '🎉',
  color: 'purple',
  description: 'Find volunteers or participants for community events',
  sections: [
    {
      id: 'event_details',
      title: 'Event Details',
      icon: '🎉',
      color: 'purple',
      fields: [
        {
          key: 'event_type',
          type: 'button_group',
          label: 'Event Type',
          required: true,
          options: [
            { value: 'volunteer', label: 'Volunteer', icon: '🙋' },
            { value: 'community_cleanup', label: 'Cleanup', icon: '🧹' },
            { value: 'fundraiser', label: 'Fundraiser', icon: '💰' },
            { value: 'workshop', label: 'Workshop', icon: '🎓' },
            { value: 'meetup', label: 'Meetup', icon: '👥' },
            { value: 'sports', label: 'Sports', icon: '⚽' },
            { value: 'cultural', label: 'Cultural', icon: '🎭' },
            { value: 'educational', label: 'Educational', icon: '📖' },
            { value: 'social', label: 'Social', icon: '🎈' },
            { value: 'other', label: 'Other', icon: '📋' },
          ],
        },
        {
          key: 'event_date',
          type: 'datetime',
          label: 'Event Date & Time',
          required: true,
          helpText: 'When does the event start?',
        },
        {
          key: 'event_duration_hours',
          type: 'number',
          label: 'Duration',
          required: true,
          min: 0.5,
          max: 24,
          step: 0.5,
          unit: 'hours',
        },
        {
          key: 'participants_needed',
          type: 'number',
          label: 'Participants Needed',
          required: true,
          min: 1,
          max: 1000,
          step: 1,
          helpText: 'How many people do you need?',
        },
      ],
    },
    {
      id: 'location',
      title: 'Location',
      fields: [
        {
          key: 'location.address',
          type: 'text',
          label: 'Address',
          required: true,
          placeholder: 'Event address',
        },
        {
          key: 'location.is_virtual',
          type: 'checkbox',
          label: 'This is a virtual event',
          required: false,
        },
        {
          key: 'location.virtual_link',
          type: 'text',
          label: 'Virtual Meeting Link',
          required: false,
          placeholder: 'https://zoom.us/...',
          helpText: 'Meeting link for virtual participants',
        },
      ],
    },
    {
      id: 'requirements',
      title: 'Requirements',
      description: 'Optional participant requirements',
      fields: [
        {
          key: 'requirements.age_minimum',
          type: 'number',
          label: 'Minimum Age',
          required: false,
          min: 0,
          max: 100,
          step: 1,
        },
        {
          key: 'requirements.background_check',
          type: 'checkbox',
          label: 'Background check required',
          required: false,
        },
        {
          key: 'requirements.experience_required',
          type: 'checkbox',
          label: 'Prior experience required',
          required: false,
        },
      ],
    },
  ],
  summary: {
    fields: ['event_type', 'event_date', 'event_duration_hours', 'participants_needed', 'location.address'],
    labels: {
      event_type: 'Type',
      event_date: 'Date',
      event_duration_hours: 'Duration',
      participants_needed: 'Participants',
      'location.address': 'Location',
    },
  },
};
