import { UISchema } from './types';

export const serviceUISchema: UISchema = {
  type: 'service',
  version: 1,
  label: 'Service Request',
  icon: '🔧',
  color: 'green',
  description: 'Request professional services, repairs, or expertise from community helpers',
  sections: [
    {
      id: 'service_details',
      title: 'Service Details',
      icon: '🔧',
      color: 'green',
      fields: [
        {
          key: 'service_category',
          type: 'button_group',
          label: 'Service Category',
          required: true,
          options: [
            { value: 'plumbing', label: 'Plumbing', icon: '🔧' },
            { value: 'electrical', label: 'Electrical', icon: '⚡' },
            { value: 'carpentry', label: 'Carpentry', icon: '🔨' },
            { value: 'tutoring', label: 'Tutoring', icon: '📚' },
            { value: 'consulting', label: 'Consulting', icon: '💼' },
            { value: 'repair', label: 'Repair', icon: '🛠️' },
            { value: 'cleaning', label: 'Cleaning', icon: '🧹' },
            { value: 'gardening', label: 'Gardening', icon: '🌱' },
            { value: 'pet_care', label: 'Pet Care', icon: '🐾' },
            { value: 'childcare', label: 'Childcare', icon: '👶' },
            { value: 'elder_care', label: 'Elder Care', icon: '👵' },
            { value: 'tech_support', label: 'Tech Support', icon: '💻' },
            { value: 'legal', label: 'Legal', icon: '⚖️' },
            { value: 'financial', label: 'Financial', icon: '💰' },
            { value: 'other', label: 'Other', icon: '📋' },
          ],
        },
        {
          key: 'skill_level_required',
          type: 'select',
          label: 'Skill Level Required',
          required: false,
          placeholder: 'Any skill level',
          options: [
            { value: 'beginner', label: 'Beginner' },
            { value: 'intermediate', label: 'Intermediate' },
            { value: 'expert', label: 'Expert' },
          ],
        },
        {
          key: 'location_type',
          type: 'button_group',
          label: 'Location Type',
          required: false,
          defaultValue: 'on_site',
          options: [
            { value: 'on_site', label: 'On-Site', icon: '🏠' },
            { value: 'remote', label: 'Remote', icon: '💻' },
            { value: 'hybrid', label: 'Hybrid', icon: '🔄' },
          ],
        },
        {
          key: 'estimated_duration_hours',
          type: 'number',
          label: 'Estimated Duration',
          required: false,
          min: 0.5,
          max: 80,
          step: 0.5,
          unit: 'hours',
          helpText: 'How long do you expect this service to take?',
        },
      ],
    },
    {
      id: 'budget',
      title: 'Budget',
      description: 'Optional budget range',
      fields: [
        {
          key: 'budget_range',
          type: 'range',
          label: 'Budget Range',
          required: false,
          min: 0,
          minLabel: 'Min',
          maxLabel: 'Max',
          unit: 'USD',
        },
      ],
    },
    {
      id: 'schedule',
      title: 'Preferred Schedule',
      description: 'When are you available?',
      fields: [
        {
          key: 'preferred_schedule.days',
          type: 'chip_select',
          label: 'Preferred Days',
          required: false,
          options: [
            { value: 'monday', label: 'Mon' },
            { value: 'tuesday', label: 'Tue' },
            { value: 'wednesday', label: 'Wed' },
            { value: 'thursday', label: 'Thu' },
            { value: 'friday', label: 'Fri' },
            { value: 'saturday', label: 'Sat' },
            { value: 'sunday', label: 'Sun' },
          ],
        },
        {
          key: 'preferred_schedule.time_of_day',
          type: 'button_group',
          label: 'Preferred Time',
          required: false,
          options: [
            { value: 'morning', label: 'Morning', icon: '🌅' },
            { value: 'afternoon', label: 'Afternoon', icon: '☀️' },
            { value: 'evening', label: 'Evening', icon: '🌆' },
            { value: 'flexible', label: 'Flexible', icon: '🔄' },
          ],
        },
      ],
    },
  ],
  summary: {
    fields: ['service_category', 'skill_level_required', 'location_type', 'estimated_duration_hours'],
    labels: {
      service_category: 'Service',
      skill_level_required: 'Skill Level',
      location_type: 'Location',
      estimated_duration_hours: 'Duration',
    },
  },
};
